name: Auto Build and Push Images

on:
  push:
    branches: [ main ]
    paths:
      - 'desktops/**'
  schedule:
    # Run weekly on Sunday at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allow manual triggering

# Add explicit permissions block
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: mollomm1

jobs:
  build-and-push-desktops:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: zorin-17
            basedesktop: "ghcr.io/mollomm1/ubuntu-22.04-base-desktop:latest"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version
        id: version
        run: |
          for version in ${{ join(matrix.distro.versions, ' ') }}; do
            echo "version=${version}" >> $GITHUB_OUTPUT
            break
          done
      
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./desktops/${{ matrix.name }}
          file: ./desktops/${{ matrix.name }}/Dockerfile
          build-args: |
            BASE_DESKTOP_IMAGE=${{ matrix.basedesktop }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/gow-${{ matrix.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max